### PR TITLE
Modifying script

### PR DESCRIPTION
**Pull request by qiaoran-abbate**
modified the shared library bash script to:
1. change the folder name to deps
2. install only necessary boost libs
3. add marker files to indicate successful installations

### CODE REVIEW

**Review by peiworld — APPROVED** [review]
it works for me.

**Comment by peiworld** [comment]
debug messages are shown because of the configuration within log4j.properties.

**Review by hakimsep04 — APPROVED** [review]
Works for me.

**Review by mk7293 — APPROVED** [review]
Works fine

**Pull request merged**
